- README.md
- docs/_config.yml
> Update link in README and config file

- docs/DeveloperGuide.md
- update product scope
- update user stories
> Update DG product scope & user stories

- docs/DeveloperGuide.md
- docs/index.md
> Update DG use cases & NFRs

- src/main/java/seedu/address/ui/MainWindow.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/MainWindow.fxml
Ui skeleton has sidebar and a placeholder for reminders
> Update Ui skeleton

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/tutorial/DeleteTutorialCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/tutorial/DeleteTutorialCommandParser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/tutorial/UniqueTutorialList.java
- src/main/java/seedu/address/model/tutorial/exceptions/TutorialNotFoundException.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/tutorial/AddTutorialCommandTest.java
- src/test/java/seedu/address/logic/commands/tutorial/DeleteTutorialCommandTest.java
- src/test/java/seedu/address/testutil/TypicalIndexes.java
- src/test/java/seedu/address/testutil/TypicalTutorials.java
Add `delete tutorial` command.
Format: `delete tutorial INDEX`
> Add `delete tutorial` command

- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/ReminderCard.java
- src/main/java/seedu/address/ui/ReminderListPanel.java
- src/main/resources/view/ReminderListCard.fxml
- src/main/resources/view/ReminderListPanel.fxml
A temporary UI for reminders to fill in the reminder placeholder.
> UI for reminder

- build.gradle
This is a compulsory task for week 10.
> Enable assertion in Gradle

- docs/DeveloperGuide.md
- docs/team/april-anh.md
- src/main/java/seedu/address/MainApp.java
- Update PPP
- Update target user (Prof to TA)
- Update user stories
> Update PPP Anh & Developer guide

- docs/UserGuide.md
Have not updated User Guide for Find command yet
> Update V1.3 user guide

- src/main/java/seedu/address/logic/commands/reminder/SortReminderByDeadline.java
- src/main/java/seedu/address/logic/commands/reminder/SortReminderByDeadlineCommand.java
- src/main/java/seedu/address/logic/commands/reminder/SortReminderByPriorityCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/datetime/Datetime.java
- src/main/java/seedu/address/model/reminder/Reminder.java
- src/main/java/seedu/address/model/reminder/ReminderDeadlineComparator.java
- src/main/java/seedu/address/model/reminder/ReminderPriorityComparator.java
- src/main/java/seedu/address/model/reminder/UniqueReminderList.java
- src/test/java/seedu/address/logic/commands/consultation/AddConsultationCommandTest.java
- src/test/java/seedu/address/logic/commands/reminder/AddReminderCommandTest.java
- src/test/java/seedu/address/logic/commands/reminder/SortReminderByDeadlineCommandTest.java
- src/test/java/seedu/address/logic/commands/reminder/SortReminderByPriorityCommandTest.java
- src/test/java/seedu/address/logic/commands/student/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/tutorial/AddTutorialCommandTest.java
Change from comparable to comparator so that it is possible to implement 2 different types of sorting methods.
Currently there are 2 methods to sorting reminders, either by deadline or priority level.
Close #70
> Sort reminders deadline

- src/main/java/seedu/address/logic/commands/ClearCommand.java
- src/main/java/seedu/address/logic/commands/reminder/MarkReminderCommand.java
- src/main/java/seedu/address/logic/commands/reminder/UnmarkReminderCommand.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/reminder/Reminder.java
- src/main/java/seedu/address/model/reminder/ReminderDescription.java
- src/main/java/seedu/address/model/reminder/ReminderStatus.java
- src/main/java/seedu/address/storage/JsonAdaptedReminder.java
- src/main/java/seedu/address/ui/ReminderCard.java
Minor code changes for better clarity
> Edit reminder status

- src/main/java/seedu/address/logic/commands/reminder/EditReminderCommand.java
- src/main/java/seedu/address/model/reminder/ReminderComplexComparator.java
- src/main/java/seedu/address/model/reminder/ReminderDeadlineComparator.java
- src/main/java/seedu/address/model/reminder/ReminderPriorityComparator.java
- src/main/java/seedu/address/model/reminder/ReminderPriorityDeadlineComparator.java
- src/main/java/seedu/address/model/reminder/UniqueReminderList.java
Allow Reminder to sort by more than one comparator at a time.
> Implemented a ComplexReminderComparator

- src/main/java/seedu/address/logic/commands/tutorial/EditTutorialCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/tutorial/EditTutorialCommandParser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/tutorial/UniqueTutorialList.java
- src/test/java/seedu/address/logic/commands/consultation/AddConsultationCommandTest.java
- src/test/java/seedu/address/logic/commands/reminder/AddReminderCommandTest.java
- src/test/java/seedu/address/logic/commands/student/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/tutorial/AddTutorialCommandTest.java
`edit tutorial` command
- works similar to `edit student` command
Parameters:
- name
- module
- venue
- timeslot
- day
> Implemented edit tutorial command

- docs/UserGuide.md
- src/main/java/seedu/address/model/student/StudentId.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/reminder/EditReminderCommandTest.java
- src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
- src/test/java/seedu/address/testutil/EditReminderDescriptorBuilder.java
Add test cases for edit reminders.
> Reminder test cases

- docs/UserGuide.md
Added links to tables sections.
See [heyzec.github.io/tp/UserGuide.html](https://heyzec.github.io/tp/UserGuide.html) to preview.
> Add links to UserGuide

- src/main/java/seedu/address/logic/commands/tutorial/EditTutorialCommand.java
- src/main/java/seedu/address/logic/parser/tutorial/AddTutorialCommandParser.java
- src/main/java/seedu/address/logic/parser/tutorial/TutorialParserUtil.java
- src/main/java/seedu/address/model/commons/ModuleCode.java
- src/main/java/seedu/address/model/commons/Venue.java
- src/main/java/seedu/address/model/tutorial/Tutorial.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedTutorial.java
- src/test/java/seedu/address/testutil/TutorialBuilder.java
Move venue and module code to common fields since they are used in both tutorial and consultation
> Refactor venue

- src/main/java/seedu/address/logic/commands/student/ExtractEmailsCommand.java
> Throw exception when "extract emails" on 0 student

- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
> Fix bug with extraneous spaces btw. command words

- src/test/java/seedu/address/logic/LogicManagerTest.java
> Change address book file path

- docs/UserGuide.md
Edit find command in UG to make it clearer
Close #153
> Edit UG find command

- src/main/java/seedu/address/model/student/Grade.java
- src/test/java/seedu/address/model/student/AttendanceTest.java
- src/test/java/seedu/address/model/student/GradeTest.java
- src/test/java/seedu/address/model/student/ParticipationTest.java
- src/test/java/seedu/address/model/student/StudentIdTest.java
- src/test/java/seedu/address/model/student/TelegramTest.java
- grade
- participation
- attendance
- telegram handle
- student id
> Student test case

- docs/UserGuide.md
minor updates to add student command
> minor updates to ug

- src/main/java/seedu/address/model/student/Grade.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/consultation/EditConsultDescriptorTest.java
- src/test/java/seedu/address/logic/commands/consultation/EditConsultationCommandTest.java
- src/test/java/seedu/address/logic/commands/student/EditStudentCommandTest.java
- src/test/java/seedu/address/testutil/EditConsultationDescriptorBuilder.java
- src/test/java/seedu/address/testutil/TypicalConsultations.java
- Add edit consultation test
- Add test for non-existing module and tutorial in `editStudentCommandTest`
- Fix sample data error (Empty string for grade throws an exception) -> change to `PENDING...`
Closes #237
> Edit consultation test cases

- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/reminder/UnmarkReminderCommand.java
> Improve User Guide
